version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.local
      args:
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SHARED_SECRET=Secret
    ports:
      - '3000:3000'
    restart: always
