FROM node:24 as compiler
ARG GITHUB_ACCESS_TOKEN
WORKDIR /work
COPY . ./
RUN npm ci && npm run build

FROM node:24 as optimizer
ARG GITHUB_ACCESS_TOKEN
WORKDIR /work
COPY . ./
RUN npm ci --omit=dev --ignore-scripts

FROM mcr.microsoft.com/devcontainers/javascript-node:5-24-bookworm
WORKDIR /usr/src/app
COPY --from=optimizer /work/node_modules ./node_modules
COPY --from=optimizer /work/package.json ./
COPY --from=compiler /work/dist ./dist
COPY --from=compiler /work/index.js ./
COPY --from=compiler /work/openapi.yml ./

CMD ["index.js"]
