name: Automatic Tests
on:
  pull_request:

  workflow_dispatch:

jobs:
  tests:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: npm install
        run: npm ci

      - name: run tests
        run: npm test -- --coverage

      - name: Save output
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: |
            coverage
