name: Build and push docker image to github registry and deploy on dev environment.

on:
    push:
        branches:
            - dev
            - petter-a-patch-1

permissions:
    contents: read
    packages: write

jobs:
    build:
        uses: ./.github/workflows/docker-build.yml
        with:
            update-package-version: false
            git-checkout-branch: dev
