name: Build and push docker image to github registry and deploy on dev environment.

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: helsingborg-stad/gdi-deploy/v1@main
        with:
          update-openapi-version: true
          openapi-spec-file: openapi.yml
          release-tag-name: sha-${{github.sha}}
          git-checkout-branch: dev

          gdi-gitops-config-repo: ${{ secrets.GDI_GITOPS_CONFIG_REPO }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          gdi-gitops-token: ${{ secrets.GDI_GITOPS_TOKEN }}
          gdi-gitops-app: ${{ secrets.GDI_GITOPS_APP }}
          gdi-gitops-env: dev

          docker-username: ${{ github.repository_owner }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
