name: Build and push docker image to github registry and deploy on dev environment.

on:
    push:
        branches:
            - dev

permissions:
    contents: read
    packages: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: ./.github/workflows/docker-build.yml
                    
