name: Build and push docker image to github registry and deploy on production environment.

on:
    release:
        types: [released]

permissions:
    contents: write
    packages: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: ./.github/workflows/docker-build.yml
              with:
                  update-package-version: true
                  extra-image-tags: |
                      type=raw,value=${{github.event.release.tag_name}}
