name: Build and push docker image to github registry and deploy on production environment.

on:
    release:
        types: [released]

permissions:
    contents: write
    packages: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - uses: actions/setup-node@v7
              with:
                  node-version: 24

            - uses: helsingborg-stad/gdi-deploy/v1@main
              with:
                  update-openapi-version: false
                  update-package-version: true
                  release-tag-name: ${{github.event.release.tag_name}}

                  gdi-gitops-config-repo: ${{ secrets.GDI_GITOPS_CONFIG_REPO }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}

                  gdi-gitops-token: ${{ secrets.GDI_GITOPS_TOKEN }}
                  gdi-gitops-app: ${{ secrets.GDI_GITOPS_APP }}
                  gdi-gitops-env: production
                  git-checkout-branch: ${{ github.event.release.target_commitish }}

                  docker-username: ${{ github.repository_owner }}
                  docker-password: ${{ secrets.GITHUB_TOKEN }}
                  extra-image-tags: |
                      type=raw,value=${{github.event.release.tag_name}}
